# This file can be used to customize dox tests as well as other test frameworks like flake8 and mypy

[tox]
envlist = py38
; envlist = py36, py38, py39
isolated_build = true

[testenv]
whitelist_externals = uv

commands =
    uv sync --dev
    uv run pytest
    uv run black --check tap_googleads/
    uv run flake8 tap_googleads
    uv run pydocstyle tap_googleads
    uv run mypy tap_googleads --exclude='tap_googleads/tests'


[flake8]
ignore = W503
max-line-length = 88
max-complexity = 10

[pydocstyle]
ignore = D105,D203,D213
